### ISSUE TITLE
Decimal separator - comma - dot

### ISSUE THREAD

**Issue by Elettrough** [ankitrohatgi/WebPlotDigitizer#114]
After the new update it gives me numeric data with comma as decimal separator. Is it possible to format the dataset changing the decimal separator with a dot? 

It is important to me cause the program I will use only support the dot. Thank you very much.

**Comment by ankitrohatgi** [comment]
Hello, what OS is this on and is your machine set to use commas for numbers (e.g. german locale)?

Maybe we need an option to switch which separator is preferred instead of automatically detecting.

**Comment by Elettrough** [comment]
Sorry I didn't specify, I'm on Windows 10 using Chrome. My machine is set to use dot as decimal separator but I still obtain commas from WebPlot Digitizer "View data" and "Download as .csv". The only case where I got dot was downloading my data as "Export all data".

Thank you very much

**Comment by ankitrohatgi** [comment]
Can you try hitting "Run" here and let me know if the 1.1 has a comma or a decimal on your machine?
http://jsfiddle.net/yyp184nb/

Thanks!

**Comment by Elettrough** [comment]
It has a comma.

**Comment by Elettrough** [comment]
I just tried "View data" and "Download as .csv" from the browser Windows Edge and it gives me numbers with dot. I don't really like that browser, but at least it's something.

**Comment by ankitrohatgi** [comment]
What does this return you in Chrome: http://jsfiddle.net/yyp184nb/1/

For some reason, your Chrome browser is picking up the wrong locale on your machine.

**Comment by xtotdam** [comment]
Also affects Firefox, I'm on 58.0b15.
Explicit choice for decimal dot or comma is really needed

**Comment by xtotdam** [comment]
I checked russian locale settings, comma is default for it, so locale should be okay. 
Nevertheless a switch will be nice:)

**Comment by zoomx** [comment]
I changed the decimal separator from comma to dot in Control Panel (it was comma) but I get commas as a separator too using the standalone version in Windows Seven, language italian.
But since the separator is semicolon I can easily change all commas in dots and vice versa.

**Comment by ankitrohatgi** [comment]
Thanks for all the feedback - I'll add an option to switch manually in the next release.

**Comment by RemiTheWarrior** [comment]
Hi all, has this issue been resolved by now ?

**Comment by xtotdam** [comment]
Hi @RemiTheWarrior 
No, it has not.
Trying to export data with comma as a column separator gives me that:
![изображение](https://user-images.githubusercontent.com/5108025/77920045-9e0cd480-72a6-11ea-9740-1ecd9b7f8cdc.png)
And it is impossible to distinguish whether it is X column or already Y.
Possibility to export it like
```
0.739,  0.092
1.305,  -0.128
1.709,  0.262
2.327,  -0.305
3.133,  0.532
3.597,  -0.440
3.875,  0.475
4.224,  -0.333
5.047,  0.837
5.491,  -0.660
5.495,  0.199
```
would really help.

**Comment by xtotdam** [comment]
Browser locale does not affect the data representation

I am using Firefox 74.0 64-bit by the way

**Comment by squasheds** [comment]
So... still not possible to chose one over the other, you really end up having to excel your way around the data just to actually extract the useful things. Still tremendously useful and all but it's definitely an essential thing to have the option to select what you need.

**Comment by pietrodigangi** [comment]
So still no fix for this issue is available?

**Comment by RemDelaporteMathurin** [comment]
@pietrodigangi no it hasn't I'm afraid

**Comment by nbehrnd** [comment]
Running the digitizer from https://apps.automeris.io/wpd/ with Firefox (78.10.0esr (64-bit)) in Linux Debian 11 bullseye / branch testing, I typically see decimal points and columns separated by a comma, like the one below:

![decimal](https://user-images.githubusercontent.com/19709084/116550693-98892000-a8e6-11eb-84f9-4ef98c413193.png)

And if I wish to alter the column separation, e.g., to deploy a semi-colon instead, this equally works just fine (exchange of the character in the separator window + click on `Format`):

![decimal_semicolon](https://user-images.githubusercontent.com/19709084/116550965-e736ba00-a8e6-11eb-8874-ffde2974b766.png)
